#!/usr/bin/env zsh

set -e

if [[ -s "$HOME/.rvm/scripts/rvm" ]]; then
    source "$HOME/.rvm/scripts/rvm"
elif [[ -s '/usr/local/rvm/scripts/rvm' ]]; then
    source '/usr/local/rvm/scripts/rvm'
fi

bundle exec jekyll build
(cd _site \
    && git add -A \
    && git commit $@)

git add _site
git commit $@
