#!/usr/bin/env zsh

set -e

if [[ -s "$HOME/.rvm/scripts/rvm" ]]; then
    source "$HOME/.rvm/scripts/rvm"
elif [[ -s '/usr/local/rvm/scripts/rvm' ]]; then
    source '/usr/local/rvm/scripts/rvm'
fi

git push $@

(cd _site && git push $@)
