FROM docker.io/ruby:2.3.1

RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen
RUN dpkg-reconfigure --frontend=noninteractive locales

RUN gem install bundler
RUN gem install rspec-core -v '3.4.1'
RUN gem install jekyll

ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8
ENV LC_ALL en_US.UTF-8

WORKDIR /usr/local/src

COPY Gemfile .
COPY Gemfile.lock .

RUN bundle install