FROM circleci/python:3.7.0-browsers

RUN sudo apt-get update 
RUN sudo apt-get install -y --no-install-recommends apt-utils
RUN sudo apt-get install -y locales
RUN sudo apt-get clean
RUN sudo sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen
RUN sudo dpkg-reconfigure --frontend=noninteractive locales

# This steps are needed to have aws cli installed on the system
#RUN apt-get -y install python3 python-pip python-dev
RUN pip install --upgrade pip
RUN pip install awscli --upgrade --user
RUN echo 'export PATH=~/.local/bin:$PATH' >>~/.bash_profile

ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8
ENV LC_ALL en_US.UTF-8

WORKDIR /usr/local/src
