- id: introduction_to_functional_programming
  name: Introduction to Functional Programming
  author: Jorge Gueorguiev García
  description: A course to learn some of the basics of functional programming for those who are already coding proficient.
  page: /services/training/introduction-to-functional-programming

- id: crafting_code
  name: Crafting Code
  author: Sandro Mancuso
  description: For developers that wanting to get better at writing clean, testable & maintainable code
  page: /services/training/crafting-code

- id: crafted_design
  name: Crafted Design
  author: Sandro Mancuso
  description: For experienced developers wanting to get better at designing well-crafted solutions.
  page: /services/training/crafted-design

- id: lambdas
  name: Microservices with AWS Lambdas
  author: Mashooq Badar
  description: Learn how to build and deploy you microservices using the AWS server-less architecture
  page: /services/training/lambda-training

- id: serverless
  name: Serverless Architecture Using AWS
  author: Mashooq Badar
  description: Learn how to take the pain out of building web apps using AWS server-less architecture
  page: /services/training/serverless-training

- id: ead
  name: Enterprise Application Development
  author: Mashooq Badar
  description: For developers wanting to learn how to build an enterprise system from scratch
  page: /services/training/enterprise-application-development

- id: fabric
  name: Building Reliable Microservices with Microsoft Service Fabric
  author: Steve Lydford
  description: Learn how to build highly available and reliable microservices with Service Fabric and Azure
  page: /services/training/service-fabric-training

- id: docker
  name: Zero to Continous Delivery with Docker
  author: Robert Firek
  description: Learn to use Docker tools to enable continuous deployment, horizontal scalability & zero downtime.
  page: /services/training/devops-training


- id: crafting_webapps
  name: Crafting Webapps
  author: Nacho García
  description: Discover how to build web applications that scale, driven by tests, and framework agnostic.
  page: /services/training/crafting-webapps