training-course-ids:
  - crafting-code
  - crafted-design
  - functional-programming
  - lambdas
  - serverless
  - ead

crafting-code-and-crafted-design:
  name: Crafting Code & Crafted Design
  course-length: 3 days
  author: Sandro Mancuso
  description: This training series is designed to enhance your team's skill set around creating expertly written code and well-crafted design. This will allow changes within your organisation to be carried out faster and more sustainably.
  page: /services/training/crafting-code-and-crafted-design

crafting-code:
  name: Crafting Code
  author: Sandro Mancuso
  description: This course is designed to improve your team's skills around creating clean, maintainable code. This will enable change to be released faster and more sustainably.
  page: /services/training/crafting-code
  featured: true
  background-image-path: /assets/custom/img/training-overview/training-backgrounds_bg-crafting-code.svg

crafted-design:
  name: Crafted Design
  author: Sandro Mancuso
  description: This course enables your teams to design well-crafted solutions. This will allow your team to be responsive to changing requirements while implementing new functionality.
  page: /services/training/crafted-design
  featured: true
  background-image-path: /assets/custom/img/training-overview/training-backgrounds_bg-crafted-design.svg

functional-programming:
  name: "Introduction to <br> Functional Programming"
  author: Jorge Gueorguiev García
  description: This course teaches your software delivery teams the basics of functional programming.
  page: /services/training/introduction-to-functional-programming
  background-image-path: /assets/custom/img/training-overview/training-backgrounds_bg-functional-programming.svg

lambdas:
  name: "Microservices with <br> AWS Lambdas"
  author: Mashooq Badar
  description: This course teaches your software delivery teams how to build and deploy microservices using AWS serverless architecture.
  page: /services/training/lambda-training
  background-image-path: /assets/custom/img/training-overview/training-backgrounds_bg-microservices-with-aws.svg

serverless:
  name: "Serverless Architecture <br> Using AWS"
  author: Mashooq Badar
  description: This course teaches your teams how to build web applications using AWS serverless architecture. Teams can release fully scalable and secure web apps with ease.
  page: /services/training/serverless-training
  background-image-path: /assets/custom/img/training-overview/training-backgrounds_bg-serverless-architecture-using-aws.svg

ead:
  name: "Enterprise Application <br> Development"
  author: Mashooq Badar
  description: This course teaches software delivery teams how to build an enterprise system using industry leading techniques.
  page: /services/training/enterprise-application-development
  background-image-path: /assets/custom/img/training-overview/training-backgrounds_bg-enterprise-application-development.svg
