- id: crafting_code
  name: Crafting Code
  author: Sandro Mancuso
  description: Para desarrolladores que quieren mejorar en escribir código limpio, testable y mantenible
  page: /services/training/crafting-code

- id: crafted_design
  name: Crafted Design
  author: Sandro Mancuso
  description: Para desarrolladores experimentados que quieren mejorar en el diseño de soluciones bien elaboradas.
  page: /services/training/crafted-design

- id: introduction_to_functional_programming
  name: Introducción a Programación Funcional
  author: Jorge Gueorguiev García
  description: Para desarrolladores experimentados que quieren aprender los conceptos básicos de programacion funcional.
  page: /services/training/introduction-to-functional-programming

- id: lambdas
  name: Microservicios con AWS Lambdas
  author: Mashooq Badar
  description: Aprenda cómo construir y desplegar sus microservicios, usando la arquitectura server-less de AWS
  page: /services/training/lambda-training

- id: serverless
  name: Arquitectura Serverless Utilizando AWS
  author: Mashooq Badar
  description: Aprenda cómo evitar los problemas de construir aplicaciones web, usando la arquitectura server-less de AWS
  page: /services/training/serverless-training

- id: ead
  name: Desarrollo de Aplicaciones Empresariales
  author: Mashooq Badar
  description: Para desarrolladores que quieren aprender cómo construir un sistema empresarial desde cero
  page: /services/training/enterprise-application-development
