training-course-ids:
  - crafting-code
  - crafted-design
  - functional-programming
  - lambdas
  - serverless
  - ead

crafting-code-and-crafted-design:
  name: Crafting Code y Crafted Design
  course-length: 3 Días
  author: Sandro Mancuso
  description: This training series is designed to enhance your team's skill set around creating expertly written code and well-crafted design. This will allow changes within your organisation to be carried out faster and more sustainably.
  page: /services/training/crafting-code-and-crafted-design

crafting-code:
  name: Crafting Code
  author: Sandro Mancuso
  description: Este curso está diseñado para mejorar las habilidades de un equipo a la hora de escribir código limpio y fácil de mantener.
  page: /services/training/crafting-code
  featured: true
  background-image-path: /assets/custom/img/training-overview/training-backgrounds_bg-crafting-code.svg

crafted-design:
  name: Crafted Design
  author: Sandro Mancuso
  description: En esta formación ayudamos a los equipos de desarrollo a mejorar sus habilidades para crear soluciones bien diseñadas.
  page: /services/training/crafted-design
  featured: true
  background-image-path: /assets/custom/img/training-overview/training-backgrounds_bg-crafted-design.svg

functional-programming:
  name: Introducción a Functional Programming
  author: Jorge Gueorguiev García
  description: Este es un curso pensado para los equipos que necesitan una introducción a los conceptos básicos de la programación funcional.
  page: /services/training/introduction-to-functional-programming
  background-image-path: /assets/custom/img/training-overview/training-backgrounds_bg-functional-programming.svg

lambdas:
  name: Microservicios con AWS Lambdas
  author: Mashooq Badar
  description: En este curso aportamos los conocimientos necesarios para que tu equipo pueda construir e implementar microservicios utilizando la arquitectura serverless  de AWS.
  page: /services/training/lambda-training
  background-image-path: /assets/custom/img/training-overview/training-backgrounds_bg-microservices-with-aws.svg

serverless:
  name: Arquitectura Serverless utilizando AWS
  author: Mashooq Badar
  description: Con esta formación tu equipo adquirirá los conocimientos y seguridad necesaros para crear aplicaciones web utilizando la arquitectura Serverless de AWS.
  page: /services/training/serverless-training
  background-image-path: /assets/custom/img/training-overview/training-backgrounds_bg-serverless-architecture-using-aws.svg

ead:
  name: Desarrollo de aplicaciones empresariales
  author: Mashooq Badar
  description: Este curso es para aquellos desarrolladores que desean aprender a construir un sistema empresarial desde cero.
  page: /services/training/enterprise-application-development
  background-image-path: /assets/custom/img/training-overview/training-backgrounds_bg-enterprise-application-development.svg
