training-course-ids:
  - crafting-code
  - crafted-design
  - functional-programming
  - lambdas
  - serverless
  - ead

crafting-code-and-crafted-design:
  name: Crafting Code <br>y Crafted Design
  course-length: 3 Días
  duration: "DURACIÓN: 3 Días"
  course-instructor-title: INSTRUCTOR DEL CURSO
  course-instructor-bio-title: INSTRUCTOR
  author: Sandro Mancuso
  description: Esta serie de capacitación está pensada para aquellos equipos que desean convertirse en expertos escribiendo código bien diseñado.
  page: /servicios/training/crafting-code-and-crafted-design
  avatar-src: /assets/custom/img/training-overview/sandro_avatar_image.png
  image-src: /assets/custom/img/training-overview/crafted-code-and-design.jpg
  title-background-image-path: /assets/custom/img/training/crafting-code-and-crafted-design/training-backgrounds_bg-crafting-code-and-design.svg
  hubspot-cta-id: 6641ee45-d332-40bd-a8d8-5d4096a0405b
  instructor-bio-p-1: <b>Software craftsman, escritor, cofundador de Codurance y fundador de la London Software Craftsmanship Community (LSCC).</b> Sandro ha estado programando desde muy joven, y comenzó su carrera profesional en 1996. Ha trabajado para startups, empresas de software , empresas de productos, empresas de consultoría internacional y bancos de inversión.
  instructor-bio-p-2: Durante su carrera, Sandro tuvo la oportunidad de trabajar en gran variedad de proyectos, con diferentes idiomas, tecnologías y en muchas industrias diferentes. Sandro tiene mucha experiencia en llevar la ideología de Software Craftsmanship y las prácticas de Programación Extrema a organizaciones de todos los tamaños. Sandro es reconocido internacionalmente por su trabajo en la evolución y difusión de Software Craftsmanship y con frecuencia es invitado como speaker en muchas conferencias en todo el mundo. Su aspiración profesional es elevar el nivel de la industria del software ayudando a los desarrolladores a mejorar y preocuparse más por su oficio.

crafting-code:
  name: Crafting Code
  author: Sandro Mancuso
  course-length: 2 Días
  duration: "DURACIÓN: 2 Días"
  course-instructor-title: INSTRUCTOR DEL CURSO
  course-instructor-bio-title: INSTRUCTOR
  description: Este curso de 2 días está diseñado para mejorar las habilidades de tu equipo en torno a la creación de código bien elaborado, comprobable y mantenible. Con un fuerte enfoque en la software craftsmanship, este curso práctico enseñará a los desarrolladores de software técnicas prácticas que pueden aplicar de inmediato a proyectos del mundo real, tanto nuevos desarrollos como bases de código legacy. Las técnicas cubiertas en este curso proporcionan la base necesaria para lanzamientos más frecuentes y seguros.
  page: /servicios/training/crafting-code
  featured: true
  background-image-path: /assets/custom/img/training/crafting-code/training-backgrounds_bg-crafting-code.svg
  instructor-bio-p-1: <b>Software craftsman, escritor, cofundador de Codurance y fundador de la London Software Craftsmanship Community (LSCC).</b> Sandro ha estado programando desde muy joven, y comenzó su carrera profesional en 1996. Ha trabajado para startups, empresas de software , empresas de productos, empresas de consultoría internacional y bancos de inversión.
  instructor-bio-p-2: Durante su carrera, Sandro tuvo la oportunidad de trabajar en gran variedad de proyectos, con diferentes idiomas, tecnologías y en muchas industrias diferentes. Sandro tiene mucha experiencia en llevar la ideología de Software Craftsmanship y las prácticas de Programación Extrema a organizaciones de todos los tamaños. Sandro es reconocido internacionalmente por su trabajo en la evolución y difusión de Software Craftsmanship y con frecuencia es invitado como speaker en muchas conferencias en todo el mundo. Su aspiración profesional es elevar el nivel de la industria del software ayudando a los desarrolladores a mejorar y preocuparse más por su oficio.

crafted-design:
  name: Crafted Design
  course-length: 2 Días
  duration: "DURACIÓN: 2 Días"
  course-instructor-title: INSTRUCTOR DEL CURSO
  course-instructor-bio-title: INSTRUCTOR
  author: Sandro Mancuso
  description: Este curso permitirá a tu equipo mejorar sus habilidades para crear soluciones bien diseñadas. Esto hara posible que tu equipo responda a las necesades cambiantes  del negocio mientras implementa nuevas funcionalidades.
  page: /servicios/training/crafted-design
  featured: true
  background-image-path: /assets/custom/img/training/crafted-design/training-backgrounds_bg-crafted-design.svg
  instructor-bio-p-1: <b>Software craftsman, escritor, cofundador de Codurance y fundador de la London Software Craftsmanship Community (LSCC).</b> Sandro ha estado programando desde muy joven, y comenzó su carrera profesional en 1996. Ha trabajado para startups, empresas de software , empresas de productos, empresas de consultoría internacional y bancos de inversión.
  instructor-bio-p-2: Durante su carrera, Sandro tuvo la oportunidad de trabajar en gran variedad de proyectos, con diferentes idiomas, tecnologías y en muchas industrias diferentes. Sandro tiene mucha experiencia en llevar la ideología de Software Craftsmanship y las prácticas de Programación Extrema a organizaciones de todos los tamaños. Sandro es reconocido internacionalmente por su trabajo en la evolución y difusión de Software Craftsmanship y con frecuencia es invitado como speaker en muchas conferencias en todo el mundo. Su aspiración profesional es elevar el nivel de la industria del software ayudando a los desarrolladores a mejorar y preocuparse más por su oficio.

functional-programming:
  name: Introducción a<br>Functional Programming
  course-length: 2 Días
  duration: "DURACIÓN: 2 Días"
  description: Con este curso tu equipo adqiuirirá los conceptos básicos de la programación funcional. Exploraremos los fundamentos del paradigma funcional en una serie de ejercicios prácticos, que proporcionarán un punto de partida para iniciarse en la programación funcional.
  page: /servicios/training/introduction-to-functional-programming
  background-image-path: /assets/custom/img/training/introduction-to-functional-programming/training-backgrounds_bg-functional-programming.svg

lambdas:
  name: Microservicios con<br>AWS Lambdas
  course-length: 2 Días
  duration: "DURACIÓN: 2 Días"
  description: En este curso aportamos los conocimientos necesarios para que tu equipo pueda construir e implementar microservicios utilizando la arquitectura serverless  de AWS.
  page: /servicios/training/lambda-training
  background-image-path: /assets/custom/img/training/lambda-training/training-backgrounds_bg-microservices-with-aws.svg

serverless:
  name: Arquitectura Serverless<br>utilizando AWS
  course-length: 2 Días
  duration: "DURACIÓN: 2 Días"
  description: Con esta formación tu equipo adquirirá los conocimientos y seguridad necesaros para crear aplicaciones web utilizando la arquitectura Serverless de AWS.
  page: /servicios/training/serverless-training
  background-image-path: /assets/custom/img/training/serverless-training/training-backgrounds_bg-serverless-architecture-using-aws.svg

ead:
  name: Desarrollo de<br>aplicaciones empresariales
  course-length: 2 Días
  duration: "DURACIÓN: 2 Días"
  description: Este curso es para aquellos desarrolladores que desean aprender a construir un sistema empresarial desde cero.
  page: /servicios/training/enterprise-application-development
  background-image-path: /assets/custom/img/training/enterprise-application-development/training-backgrounds_bg-enterprise-application-development.svg
