- id: crafting_code
  name: Crafting Code
  author: Sandro Mancuso
  description: For developers that wanting to get better at writing clean, testable & maintainable code
  page: /services/training/crafting-code
  featured: true

- id: crafted_design
  name: Crafted Design
  author: Sandro Mancuso
  description: For experienced developers wanting to get better at designing well-crafted solutions.
  page: /services/training/crafted-design
  featured: true

- id: introduction_to_functional_programming
  name: "Introduction to <br> Functional Programming"
  author: Jorge Gueorguiev García
  description: A course to learn some of the basics of functional programming for those who are already coding proficient.
  page: /services/training/introduction-to-functional-programming

- id: lambdas
  name: "Microservices with <br> AWS Lambdas"
  author: Mashooq Badar
  description: Learn how to build and deploy you microservices using the AWS server-less architecture
  page: /services/training/lambda-training

- id: serverless
  name: "Serverless Architecture <br> Using AWS"
  author: Mashooq Badar
  description: Learn how to take the pain out of building web apps using AWS server-less architecture
  page: /services/training/serverless-training

- id: ead
  name: "Enterprise Application <br> Development"
  author: Mashooq Badar
  description: For developers wanting to learn how to build an enterprise system from scratch
  page: /services/training/enterprise-application-development
